<?php

/**
 * @file
 * Contains cmc_redhen.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cmc_redhen_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cmc_redhen module.
    case 'help.page.cmc_redhen':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CMC Redhen') . '</p>';
      return $output;

    default:
  }
}
