<?php

/**
 * @file
 * Contains cmc_test_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cmc_test_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cmc_test_content module.
    case 'help.page.cmc_test_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test content for CMC') . '</p>';
      return $output;

    default:
  }
}
