q1:
  political:
    tids:
      - '6'
  religious:
    tids:
      - '2'
  sports:
    tids:
      - '3'
q2:
  Welcome_people_at_front_door:
    tids:
      - '4'
  Learn_how_to_operate_a_camera:
    tids:
      - '9'
  Edit_a_production:
    tids:
      - '6'
      - '8'
favorite_athlete:
  lebron:
    tids:
      - '8'
      - '3'
  tennis:
    tids:
      - '5'
favorite_nba_team_:
  chicago_bulls:
    tids:
      - '10'
