dependencies:
  enforced:
    module:
      - redhen_contact
unique_email: true
required_properties:
  first_name: first_name
  last_name: last_name
  middle_name: 0
connect_users: false
embed_on_user_form: false
alter_username: 1
registration: 0
registration_type: individual
registration_link: 0
registration_update: 0
_core:
  default_config_hash: jEXZsrgdvtYGXDQuvNfzXFlq7EznLySGCnqDskwrl9o
valid_email: 0
contact_user_form: default
registration_form: default
